services:
  - type: web
    name: orbit-backend
    env: node
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render will override this with its own port
      - key: MONGODB_URI
        sync: false # You'll need to set this in the Render dashboard
